apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  # Including defined template values
  labels: {{- include "labels" . | nindent 4 }}
{{/*
This comment block will get ignored in the YAML format. Instead of this we can use hash (#). 
*/}}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: app-nginx
  template:
    metadata:
      labels:
        app: app-nginx
    spec:
      containers:
        - name: {{ .Values.deployment.containerName }}
          image: "{{ .Values.deployment.image.app }}:{{ .Values.deployment.image.version }}"


