# Default values for chart-2.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Deployment section
deployment:
  name: app-nginx
  image:
    app: nginx
    version: alpine
  replicaCount: 2
  containerName: test-nginx  

# Service section
service:
  name: app-service
  targetPort: 80
  nodePort: 32565
  type: NodePort
  port: 80